version: 2
jobs:
  build:
    docker:
      - image: coqorg/coq:8.6
      - image: coqorg/coq:8.7
      - image: coqorg/coq:8.8
      - image: coqorg/coq:8.9
      - image: coqorg/coq:8.10
      - image: coqorg/coq:latest
    steps:
      - checkout
      - run: |
          ./configure.sh
          make
          make -j html
      - persist_to_workspace:
          root: html
          paths: .
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@example.com"
            git config user.name "ci-build"
      - run: ls -la
      - add_ssh_keys:
          fingerprints:
            - "43:6a:63:b2:f7:1b:f8:ba:a1:e2:48:40:f1:3b:a8:71"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --message "[skip ci] doc upload" --dist .

workflows:
  version: 2
  build:
    jobs:
      - build
      - docs-deploy:
          requires:
            - build
          filters:
            branches:
              only: master
